security:
    encoders:
            App\Entity\User:
                algorithm: bcrypt
                cost: 12

    providers:
        provider:
            entity:
                class:    App\Entity\User
                property: email

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        global:
            pattern:    ^/
            provider:   provider
            anonymous:  ~
            access_denied_handler: App\Security\AccessDeniedHandler

            form_login:
                login_path:                     login
                check_path:                     login
                default_target_path:            homepage
                always_use_default_target_path: false
            logout:
                path:     /logout
                target:   /
            remember_me:
                secret:                '%kernel.secret%'
                path:                  /
                remember_me_parameter: '_remember_me'
                secure:                true

    access_control:
        # Block authenticated users from accessing login or registration
        # pages via URL.
        - { path: ^/login, allow_if: "!is_fully_authenticated()"}
        - { path: ^/register,  allow_if: "!is_fully_authenticated()" }

        # Prevent unauthenticated users from accessing certain pages
        - { path: ^/user, roles: ROLE_USER }
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
